# Generated by Django 5.1.15 on 2026-09-26 09:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Stable identifier shared by all versions, e.g. PAYE_RESIDENT', max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('TAX', 'Income tax (PAYE)'), ('SOCIAL_SECURITY', 'Social security'), ('LEVY', 'Employer levy'), ('OTHER', 'Other statutory')], max_length=20)),
                ('party', models.CharField(choices=[('EMPLOYEE', 'Employee deduction'), ('EMPLOYER', 'Employer contribution')], max_length=10)),
                ('method', models.CharField(choices=[('PROGRESSIVE', 'Progressive tax brackets'), ('FLAT_RATE', 'Flat percentage of base'), ('FIXED_AMOUNT', 'Fixed amount per period')], max_length=15)),
                ('base', models.CharField(choices=[('BASIC', 'Basic salary (after proration/unpaid leave)'), ('GROSS', 'Gross earnings'), ('SOCIAL_SECURITY_BASE', 'Earnings flagged for social security'), ('TAXABLE_INCOME', 'Taxable income (taxable earnings less pre-tax deductions)'), ('CASH_EMOLUMENTS', 'Gross cash emoluments')], max_length=24)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, help_text='Percent, for FLAT_RATE', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('base_ceiling', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum base the rate applies to (cap).', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum contribution per period.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reduces_taxable_income', models.BooleanField(default=False, help_text='Employee contribution deducted before computing taxable income.')),
                ('residency', models.CharField(choices=[('ALL', 'All employees'), ('RESIDENT', 'Tax residents only'), ('NON_RESIDENT', 'Non-residents only')], default='ALL', max_length=12)),
                ('applies_to_schemes', models.JSONField(blank=True, default=list, help_text='Social-security schemes this rule applies to, e.g. ["NSSF"]. Empty = all employees.')),
                ('min_employee_count', models.PositiveIntegerField(blank=True, help_text='Rule only applies when the payroll has at least this many employees.', null=True)),
                ('calculation_order', models.PositiveSmallIntegerField(default=100)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_name', models.CharField(blank=True, help_text='e.g. Tanzania Revenue Authority', max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_reference', models.CharField(blank=True, help_text='Act/section/notice reference', max_length=255)),
                ('source_retrieved_on', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified against official source')], db_index=True, default='UNVERIFIED', max_length=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'statutory_rules',
                'ordering': ['calculation_order', 'code', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, help_text='Blank = no upper limit', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='statutory.statutoryrule')),
            ],
            options={
                'db_table': 'tax_brackets',
                'ordering': ['rule', 'lower_bound'],
            },
        ),
        migrations.AddConstraint(
            model_name='statutoryrule',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='uniq_rule_code_version'),
        ),
        migrations.AddConstraint(
            model_name='statutoryrule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='rule_to_after_from'),
        ),
        migrations.AddConstraint(
            model_name='taxbracket',
            constraint=models.UniqueConstraint(fields=('rule', 'lower_bound'), name='uniq_bracket_lower'),
        ),
        migrations.AddConstraint(
            model_name='taxbracket',
            constraint=models.CheckConstraint(condition=models.Q(('upper_bound__isnull', True), ('upper_bound__gt', models.F('lower_bound')), _connector='OR'), name='bracket_upper_gt_lower'),
        ),
    ]
