# Generated by Django 5.1.15 on 2026-09-26 09:52

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bravado Company Ltd', max_length=200)),
                ('address', models.TextField(blank=True, default='Dar es Salaam, Tanzania')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('tin', models.CharField(blank=True, max_length=50, verbose_name='Company TIN')),
                ('nssf_employer_number', models.CharField(blank=True, max_length=50)),
                ('wcf_registration_number', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', validators=[apps.core.validators.validate_image_upload])),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('proration_basis', models.CharField(choices=[('CALENDAR_DAYS', 'Calendar days in period'), ('FIXED_30_DAYS', 'Fixed 30-day month')], default='CALENDAR_DAYS', max_length=20)),
                ('rounding_decimals', models.PositiveSmallIntegerField(default=2)),
                ('require_verified_rules_for_approval', models.BooleanField(default=True, help_text='Block payroll approval when a statutory rule used in the calculation is not verified.')),
                ('enforce_segregation_of_duties', models.BooleanField(default=True, help_text='The user who calculated a payroll may not approve it.')),
                ('payslip_footer', models.TextField(blank=True, default='This is a computer-generated payslip and does not require a signature.')),
                ('statutory_disclaimer', models.TextField(default='Statutory calculations (PAYE, social security, WCF, SDL and other levies) are driven by configurable rules. They must be reviewed against current official Tanzanian requirements (TRA, NSSF, PSSSF, WCF) before payroll is finalized.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'company settings',
                'db_table': 'company_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('rounding_decimals__lte', 4)), name='company_rounding_lte_4')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_CHANGE', 'Password Change'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('PAYROLL_CALCULATE', 'Payroll Calculate'), ('PAYROLL_STATUS', 'Payroll Status'), ('PAYROLL_APPROVE', 'Payroll Approve'), ('PAYROLL_CLOSE', 'Payroll Close'), ('PAYSLIP_GENERATE', 'Payslip Generate'), ('PAYMENT_RECORD', 'Payment Record'), ('PERMISSION_CHANGE', 'Permission Change'), ('EXPORT', 'Export')], db_index=True, max_length=32)),
                ('model', models.CharField(blank=True, db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['model', 'object_id'], name='audit_logs_model_fdf4ea_idx')],
            },
        ),
    ]
