# Generated by Django 5.1.15 on 2026-09-26 09:52

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employment_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(max_length=30, unique=True, verbose_name='Employee ID')),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNSPECIFIED', 'Prefer not to say')], max_length=12)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\+?[0-9 ()-]{7,20}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('employment_start_date', models.DateField()),
                ('employment_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On leave'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('RESIGNED', 'Resigned'), ('RETIRED', 'Retired')], db_index=True, default='ACTIVE', max_length=12)),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank transfer'), ('MOBILE', 'Mobile money'), ('CASH', 'Cash / cheque')], default='BANK', max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_branch', models.CharField(blank=True, max_length=120)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=40)),
                ('bank_swift_code', models.CharField(blank=True, max_length=20)),
                ('mobile_money_number', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\+?[0-9 ()-]{7,20}$', 'Enter a valid phone number.')])),
                ('tin', models.CharField(blank=True, max_length=30, verbose_name='TIN')),
                ('is_tax_resident', models.BooleanField(default=True)),
                ('social_security_scheme', models.CharField(choices=[('NSSF', 'NSSF'), ('PSSSF', 'PSSSF'), ('NONE', 'Not a member'), ('OTHER', 'Other')], default='NSSF', max_length=10)),
                ('social_security_number', models.CharField(blank=True, max_length=40)),
                ('wcf_number', models.CharField(blank=True, max_length=40, verbose_name='WCF number')),
                ('national_id', models.CharField(blank=True, max_length=40, verbose_name='NIDA number')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\+?[0-9 ()-]{7,20}$', 'Enter a valid phone number.')])),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=60)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.employmenttype')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='employees.department')),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(max_length=40, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('working_hours_per_week', models.DecimalField(decimal_places=2, default=Decimal('40'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('168'))])),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/%Y/', validators=[apps.core.validators.validate_document_upload])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('SUPERSEDED', 'Superseded')], db_index=True, default='DRAFT', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='employees.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='employees.employee')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='employees.employmenttype')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='employees.position')),
            ],
            options={
                'db_table': 'employment_contracts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.position'),
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_records', to='employees.employmentcontract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to='employees.employee')),
            ],
            options={
                'db_table': 'salary_history',
                'ordering': ['employee', '-effective_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('title', 'department'), name='uniq_position_per_department'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('basic_salary__gte', 0)), name='contract_salary_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='contract_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='employees_last_na_b924c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('employment_end_date__isnull', True), ('employment_end_date__gte', models.F('employment_start_date')), _connector='OR'), name='employee_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='salaryrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_from'), name='uniq_salary_effective_from'),
        ),
        migrations.AddConstraint(
            model_name='salaryrecord',
            constraint=models.CheckConstraint(condition=models.Q(('basic_salary__gte', 0)), name='salary_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salaryrecord',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='salary_to_after_from'),
        ),
    ]
