# Generated by Django 5.1.15 on 2026-09-26 09:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ALLOWANCE', 'Allowance'), ('OVERTIME', 'Overtime'), ('BONUS', 'Bonus'), ('COMMISSION', 'Commission'), ('OTHER', 'Other earning')], default='ALLOWANCE', max_length=12)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed amount'), ('PERCENT_OF_BASIC', 'Percentage of basic salary'), ('HOURS_X_RATE', 'Quantity x rate (e.g. overtime hours)')], default='FIXED', max_length=20)),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('default_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Percent (e.g. 10 = 10%) or rate per unit', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_taxable', models.BooleanField(help_text='Included in taxable income for PAYE.')),
                ('is_social_security_base', models.BooleanField(help_text='Included in the base for social-security contributions (e.g. NSSF).')),
                ('is_cash_emolument', models.BooleanField(default=True, help_text='Counts as gross cash emolument for employer levies (e.g. SDL/WCF).')),
                ('is_recurring', models.BooleanField(default=True)),
                ('prorate', models.BooleanField(default=True, help_text='Pro-rate recurring amounts when the employee joins/leaves mid-period.')),
                ('is_active', models.BooleanField(default=True)),
                ('treatment_reference', models.CharField(blank=True, help_text='Legal/regulatory basis for the tax treatment chosen.', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'allowance_types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('STATUTORY', 'Statutory'), ('LOAN', 'Loan repayment'), ('ADVANCE', 'Salary advance'), ('INSURANCE', 'Insurance'), ('PENSION', 'Pension / voluntary social security'), ('UNION', 'Union dues'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed amount'), ('PERCENT_OF_BASIC', 'Percentage of basic salary'), ('PERCENT_OF_GROSS', 'Percentage of gross earnings')], default='FIXED', max_length=20)),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('default_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap per period, if any.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_statutory', models.BooleanField(default=False)),
                ('reduces_taxable_income', models.BooleanField(default=False, help_text='Deducted before PAYE is computed (only where the law permits).')),
                ('is_recurring', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deduction_types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_type', models.CharField(choices=[('LOAN', 'Loan'), ('ADVANCE', 'Salary advance')], default='LOAN', max_length=10)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Flat interest % on principal', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_repayable', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('number_of_installments', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(help_text='First payroll period that includes this date starts deductions.')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='employees.employee')),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('PAYROLL', 'Payroll deduction'), ('MANUAL', 'Manual payment')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='compensation.loan')),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayments', to='payroll.payrollperiod')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_repayments',
                'ordering': ['loan', 'date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the type default for FIXED.', max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate', models.DecimalField(blank=True, decimal_places=4, help_text='Overrides the type default rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Hours/units for HOURS_X_RATE', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=True, help_text='Non-recurring items are paid once, in the period containing effective_from.')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='compensation.allowancetype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowances', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_allowances',
                'ordering': ['employee', 'allowance_type'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='emp_allowance_amount_gte_0'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='emp_allowance_to_after_from')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='compensation.deductiontype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_deductions',
                'ordering': ['employee', 'deduction_type'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='emp_deduction_amount_gte_0'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='emp_deduction_end_after_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('principal__gt', 0)), name='loan_principal_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('installment_amount__gt', 0)), name='loan_installment_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='loanrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='loan_repayment_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='loanrepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('payroll_period__isnull', False)), fields=('loan', 'payroll_period'), name='uniq_loan_repayment_per_period'),
        ),
    ]
