# Generated by Django 5.1.15 on 2026-09-26 10:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancetype',
            name='default_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Percent (e.g. 10 = 10%) or rate per unit', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='deductiontype',
            name='default_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='employeeallowance',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Overrides the type default rate.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='employeededuction',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Flat interest % on principal', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
